Repository pasqal-io/qadence2-ir, pull requests merged in 2024-11, with the labels that each got.

#10 Add python version 3.12 and 3.13 to testing matrices
  .github/workflows/test.yml
  pyproject.toml
Labels: testing

#11 [Testing] Add tests for the AST class
  qadence2_ir/irast.py
  tests/conftest.py
  tests/test_irast.py
Labels: testing

#7 [Testing] Adding unit tests to all classes and functions in types.py
  pyproject.toml
  qadence2_ir/types.py
  tests/conftest.py
  tests/test_types.py
Labels: testing

#13 [Testing] Improve tests on factory tools
  qadence2_ir/factory_tools.py
  qadence2_ir/irast.py
  tests/test_factory_tools.py
  tests/test_irast.py
Labels: testing

#15 Add test for the factory module
  tests/__init__.py
  tests/conftest.py
  tests/test_factory.py
Labels: testing

#16 Bump version to 0.1.3
  pyproject.toml
Labels: release

#17 Documentation infrastructure
  README.md
  docs/api/factory.md
  docs/api/factory_tools.md
  docs/api/index.md
  docs/api/irast.md
  docs/api/irbuilder.md
  docs/api/types.md
  docs/contents/tbd.md
  docs/extras/css/colors.css
  docs/extras/css/home.css
  docs/extras/css/mkdocstrings.css
  docs/extras/overrides/home.html
  docs/getting_started/CODE_OF_CONDUCT.md
  docs/getting_started/CONTRIBUTING.md
  docs/getting_started/LICENSE.md
  docs/getting_started/installation.md
  docs/index.md
  docs/sample_page.md
  docs/tutorials/index.md
  mkdocs.yml
Labels: documentation, infra

#20 [Infra] Fix and complete Renovate syntax.
  renovate.json
Labels: infra
